name: Release Charts

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.1

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Update chart dependencies
        run: |
          helm dependency update charts/wakapi

      - name: Package and release chart
        run: |
          # Create release packages directory
          mkdir -p .cr-release-packages

          # Package the chart
          helm package charts/wakapi -d .cr-release-packages

          # Get chart info
          CHART_VERSION=$(helm show chart charts/wakapi | grep '^version:' | cut -d' ' -f2)
          CHART_NAME="wakapi"
          RELEASE_NAME="${CHART_NAME}-${CHART_VERSION}"
          PACKAGE_FILE=".cr-release-packages/${CHART_NAME}-${CHART_VERSION}.tgz"

          # Check if release already exists
          if gh release view "$RELEASE_NAME" >/dev/null 2>&1; then
            echo "Release $RELEASE_NAME already exists, skipping..."
          else
            # Create GitHub release
            gh release create "$RELEASE_NAME" \
              --title "$RELEASE_NAME" \
              --notes "A Helm chart for self hosted Wakapi server" \
              "$PACKAGE_FILE"
            echo "Created release $RELEASE_NAME"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Pages Workflow
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/pages.yml/dispatches \
            -d '{"ref":"main"}'
